### ISSUE TITLE
Getting Errors that QT is Missing

### ISSUE THREAD

**Issue by jrock2004** [shinas101/Anime-sddm-theme#1]
Trying to use your theme and when SDDM loads I get QT errors. What dependencies do I need to install?

**Comment by shinas101** [comment]
can you please share the errors ?

try running : 

`sudo apt-get -y install qml-module-qtquick-controls`                      
`sudo apt-get install -y qml-module-qtgraphicaleffects` 
`sudo apt install qml-module-qtquick-layouts`
